name: Belajar_Hewan
description: "Aplikasi interaktif untuk belajar tentang hewan."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  sqflite: ^2.4.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  audioplayers: ^6.5.1

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/ikan/ikan.png
    - assets/images/ikan/ikan_kepala.png
    - assets/images/ikan/ikan_badan.png
    - assets/images/ikan/ikan_ekor.png
    - assets/images/ikan/ikan_sirip.png
    - assets/images/ayam/ayam.png
    - assets/images/ayam/ayam_bulu.png
    - assets/images/ayam/ayam_ceker.png
    - assets/images/ayam/ayam_ekor.png
    - assets/images/ayam/ayam_jengger.png
    - assets/images/ayam/ayam_kepala.png
    - assets/images/ayam/ayam_paruh.png
    - assets/images/ayam/ayam_sayap.png
    - assets/images/gajah/gajah.png
    - assets/images/gajah/gajah_belalai.png
    - assets/images/gajah/gajah_ekor.png
    - assets/images/gajah/gajah_gading.png
    - assets/images/gajah/gajah_kaki.png
    - assets/images/gajah/gajah_kepala.png
    - assets/images/gajah/gajah_telinga.png
    - assets/images/cicak/cicak.png
    - assets/images/cicak/cicak_kepala.png
    - assets/images/cicak/cicak_ekor.png
    - assets/images/cicak/cicak_badan.png
    - assets/images/cicak/cicak_kaki.png
    - assets/images/cicak/cicak_lidah.png
    - assets/ui/audio.png
    - assets/ui/board_a.png
    - assets/ui/board_q.png
    - assets/ui/board_q_pic.png
    - assets/ui/btn_back.png
    - assets/ui/btn_blue.png
    - assets/ui/btn_red.png
    - assets/ui/btn_green.png
    - assets/ui/btn_x.png
    - assets/ui/landing.png
    - assets/ui/btn_title.png
    - assets/audio/gajah.mp3
    - assets/audio/ayam.mp3
    - assets/audio/cicak.mp3
